export const ADD_ARTICLE = 'ADD_ARTICLE';
export const REMOVE_ARTICLE = 'REMOVE_ARTICLE';
export const REMOVE_ALL_ARTICLES = 'REMOVE_ALL_ARTICLES';
export const FOUND_BAD_WORD = 'FOUND_BAD_WORD';
export const DATA_REQUESTED = 'DATA_REQUESTED';
export const DATA_LOADED = 'DATA_LOADED';
export const API_ERRORED = 'API_ERRORED';